Vagrant.configure("2") do |config|

    config.vm.define "nomad" do |c|
        c.vm.hostname = "nomad-server"
        c.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
        c.vm.box = "debian/bullseye64"
        c.vm.network "private_network", ip: "192.168.56.8"
        c.vm.provision "ansible" do |ansible|
            ansible.playbook = "images/nomad.playbook.yml"
            ansible.extra_vars = {
            }
        end
    end

end
